#!/usr/bin/env python

from gradelib import *

r = Runner()


@test(5, "tree command with public testcase 0")
def test_tree_0():
    r.run_qemu(shell_script([
        'testgen',
        'tree os2202',
    ]))
    r.match(
        'os2202 [error opening dir]',
        '',
        '0 directories, 0 files',
    )


@test(5, "tree command with public testcase 1")
def test_tree_1():
    r.run_qemu(shell_script([
        # 'testgen',
        'tree os2202/',
    ]))
    r.match(
        'os2202/ [error opening dir]',
        '',
        '0 directories, 0 files',
    )


@test(5, "tree command with public testcase 2")
def test_tree_2():
    r.run_qemu(shell_script([
        # 'testgen',
        'tree os2022',
    ]))
    r.match(
        'os2022',
        '|',
        '+-- d1',
        '|',
        '+-- d2',
        '|   |',
        '|   +-- a',
        '|   |',
        '|   +-- b',
        '|   |',
        '|   +-- c',
        '|',
        '+-- d3',
        '    |',
        '    +-- a',
        '    |',
        '    +-- b',
        '',
        '6 directories, 2 files',
    )


@test(5, "tree command with public testcase 3")
def test_tree_3():
    r.run_qemu(shell_script([
        # 'testgen',
        'tree os2022/',
    ]))
    r.match(
        'os2022/',
        '|',
        '+-- d1',
        '|',
        '+-- d2',
        '|   |',
        '|   +-- a',
        '|   |',
        '|   +-- b',
        '|   |',
        '|   +-- c',
        '|',
        '+-- d3',
        '    |',
        '    +-- a',
        '    |',
        '    +-- b',
        '',
        '6 directories, 2 files',
    )


@test(10, "tree command with public testcase 4")
def test_tree_4():
    r.run_qemu(shell_script([
        # 'testgen',
        'tree a',
    ]))
    r.match(
        'a',
        '|',
        '+-- 0',
        '|',
        '+-- 1',
        '|',
        '+-- 2',
        '|',
        '+-- 3',
        '|',
        '+-- 4',
        '|',
        '+-- 5',
        '|',
        '+-- 6',
        '|',
        '+-- 7',
        '|',
        '+-- 8',
        '|',
        '+-- 9',
        '|',
        '+-- 10',
        '',
        '11 directories, 0 files',
    )

@test(10, "tree command with public testcase 5")
def test_tree_5():
    r.run_qemu(shell_script([
        # 'testgen',
        'tree a/',
    ]))
    r.match(
        'a/',
        '|',
        '+-- 0',
        '|',
        '+-- 1',
        '|',
        '+-- 2',
        '|',
        '+-- 3',
        '|',
        '+-- 4',
        '|',
        '+-- 5',
        '|',
        '+-- 6',
        '|',
        '+-- 7',
        '|',
        '+-- 8',
        '|',
        '+-- 9',
        '|',
        '+-- 10',
        '',
        '11 directories, 0 files',
    )

run_tests()
